// Generated by https://quicktype.io

/* export interface Tag {
    count:     number;
    total:     number;
    _embedded: Embedded;
}*/

export interface Embedded {
    _embedded: TagElement[];
} 

export interface TagElement {
    created_at: string;
    updated_at: string;
    value:      string;
    _links:     Links;
}

export interface Links {
    self: Self;
}

export interface Self {
    href: string;
}
